<a href="https://colab.research.google.com/github/RocketRikky/Secure_and_Private_AI/blob/master/Health_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
num_teachers = 10 #working with 10 hospitals
num_examples = 10000 
num_labels = 10

In [0]:
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int)

In [0]:
preds

array([[3, 6, 8, ..., 0, 7, 8],
       [0, 3, 6, ..., 8, 2, 2],
       [6, 8, 6, ..., 4, 8, 7],
       ...,
       [8, 1, 9, ..., 6, 7, 8],
       [5, 0, 8, ..., 3, 4, 2],
       [4, 8, 8, ..., 4, 9, 6]])

In [0]:
preds[0].shape

(10000,)

In [0]:
preds[:,0]
# this is telling that the first element is predicting label 3, second element is predicting label 0 and so on

array([3, 0, 6, 3, 2, 6, 2, 8, 5, 4])

In [0]:
an_image = preds[:,0]
an_image

array([3, 0, 6, 3, 2, 6, 2, 8, 5, 4])

In [0]:
label_counts = np.bincount(an_image, minlength=num_labels)
# in an_image, 0 appeared 1 time and 2 appeared 2 times and so on.

In [0]:
epsilon = 0.1
beta = 1 / epsilon

for i in range(len(label_counts)):
  label_counts[i] += np.random.laplace(0, beta, 1)

In [0]:
label_counts

array([  5,   0, -20,   0, -14,   0,   8, -11,  -4, -14])

In [0]:
new_label = np.argmax(label_counts)

In [0]:
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int).transpose(1,0)

In [0]:
new_labels = list()
for an_image in preds:
  
  label_counts = np.bincount(an_image, minlength=num_labels)
  
  epsilon = 0.1
  beta = 1 / epsilon
  
  for i in range(len(label_counts)):
    label_counts[i] += np.random.laplace(0, beta, 1)
    
  new_label = np.argmax(label_counts)
  
  new_labels.append(new_label)

In [0]:
len(new_labels)

10000

In [0]:
new_labels

[9,
 0,
 6,
 8,
 4,
 3,
 0,
 9,
 0,
 4,
 5,
 5,
 0,
 6,
 3,
 7,
 7,
 6,
 6,
 0,
 9,
 5,
 8,
 3,
 7,
 4,
 1,
 7,
 5,
 3,
 6,
 2,
 2,
 8,
 0,
 1,
 3,
 5,
 3,
 1,
 2,
 6,
 5,
 8,
 6,
 1,
 1,
 4,
 2,
 8,
 2,
 9,
 6,
 0,
 7,
 8,
 4,
 5,
 7,
 0,
 4,
 4,
 8,
 0,
 7,
 6,
 4,
 4,
 3,
 5,
 5,
 1,
 6,
 2,
 9,
 9,
 9,
 5,
 9,
 9,
 1,
 3,
 2,
 8,
 7,
 6,
 8,
 1,
 0,
 9,
 5,
 9,
 8,
 4,
 5,
 8,
 2,
 5,
 9,
 6,
 0,
 1,
 0,
 8,
 5,
 4,
 5,
 1,
 7,
 9,
 4,
 7,
 4,
 3,
 9,
 8,
 7,
 4,
 9,
 1,
 2,
 7,
 4,
 4,
 8,
 1,
 9,
 7,
 2,
 2,
 7,
 8,
 0,
 3,
 6,
 9,
 1,
 6,
 1,
 2,
 3,
 9,
 4,
 4,
 0,
 7,
 5,
 3,
 7,
 9,
 2,
 3,
 4,
 0,
 5,
 9,
 1,
 8,
 4,
 0,
 7,
 5,
 4,
 9,
 2,
 5,
 5,
 8,
 7,
 4,
 8,
 6,
 4,
 4,
 5,
 4,
 4,
 9,
 9,
 0,
 1,
 8,
 4,
 0,
 3,
 8,
 9,
 5,
 6,
 9,
 8,
 1,
 1,
 0,
 3,
 0,
 3,
 2,
 3,
 1,
 5,
 2,
 0,
 2,
 3,
 2,
 8,
 6,
 5,
 7,
 6,
 8,
 1,
 3,
 2,
 3,
 0,
 2,
 8,
 7,
 1,
 3,
 5,
 9,
 1,
 5,
 7,
 4,
 7,
 9,
 7,
 4,
 2,
 3,
 8,
 6,
 6,
 3,
 1,
 5,
 4,
 3,
 8,
 8,
 3,
 0,
 8,
 6,
 5,
 8,


PATE Analysis

In [0]:
labels = np.array([9, 9, 3, 6, 9, 9, 9, 9, 8, 2])
counts = np.bincount(labels, minlength=10)
query_result = np.argmax(counts)
query_result

9

In [0]:
!pip install syft

     |████████████████████████████████| 256kB 4.8MB/s 
     |████████████████████████████████| 204kB 44.9MB/s 
     |████████████████████████████████| 2.1MB 44.9MB/s 
     |████████████████████████████████| 256kB 48.6MB/s 
     |████████████████████████████████| 460kB 40.3MB/s 
     |████████████████████████████████| 389kB 38.7MB/s 
     |████████████████████████████████| 81kB 23.6MB/s 
     |████████████████████████████████| 266kB 46.2MB/s 
     |████████████████████████████████| 51kB 18.3MB/s 
     |████████████████████████████████| 122kB 39.2MB/s 
  Created wheel for zstd: filename=zstd-1.4.1.0-cp36-cp36m-linux_x86_64.whl size=1067080 sha256=dd8203dc5980ffb81a2785f866c77b6bf1af804ce1f2d9fd23e89469e6f66391
  Stored in directory: /root/.cache/pip/wheels/66/3f/ee/ac08c81af7c1b24a80c746df669ea3cb37542d27877d66ccf4
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44105 sha256=2825773d365772ed9d612e05ad4754b1abeb58834400bf53f639325f0f5b27f0
  Stored in di

In [0]:
from syft.frameworks.torch.differential_privacy import pate

W0817 09:21:30.972918 139835399337856 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0817 09:21:30.990077 139835399337856 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
num_teachers, num_examples, num_labels = (100, 100, 10)
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int) #fake preds
true_indices = (np.random.rand(num_examples) * num_labels).astype(int) #true answers

In [0]:
data_dep_eps, data_inde_eps = pate.perform_analysis(teacher_preds=preds, indices=true_indices, noise_eps=0.1, delta=1e-5)
print("Data Independent Epsilon: ", data_inde_eps)
print("Data dependent Epsilon: ", data_dep_eps)

Data Independent Epsilon:  11.756462732485115
Data dependent Epsilon:  11.756462732485105


In [0]:
preds[:,0:5] *= 0

In [0]:
data_dep_eps, data_inde_eps = pate.perform_analysis(teacher_preds=preds, indices=true_indices, noise_eps=0.1, delta=1e-5)
print("Data Independent Epsilon: ", data_inde_eps)
print("Data dependent Epsilon: ", data_dep_eps)

Data Independent Epsilon:  11.756462732485115
Data dependent Epsilon:  7.612485787172064


In [0]:
preds[:,0:50] *= 0

In [0]:
data_dep_eps, data_inde_eps = pate.perform_analysis(teacher_preds=preds, indices=true_indices, noise_eps=0.1, delta=1e-5)
print("Data Independent Epsilon: ", data_inde_eps)
print("Data dependent Epsilon: ", data_dep_eps)

Data Independent Epsilon:  11.756462732485115
Data dependent Epsilon:  1.52655213289881


Where to go from here?

Read: 

- Algo Foundations of Differential Privacy
- Deep Learrning with DP: arxiv.org/pdf/1607.00133.pdf

Topics:

- The Exponential Mechanism
- The Moment's Accountant
- DP SGD

Advice:

- For deployments - stick with public frameworks!
- Join DP Community
- Don't get ahead of yourself - DP still in its early days.